<?php return array (
  'sans-serif' => array(
    'normal' => $fontDir . '/Helvetica',
    'bold' => $fontDir . '/Helvetica-Bold',
    'italic' => $fontDir . '/Helvetica-Oblique',
    'bold_italic' => $fontDir . '/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $fontDir . '/Helvetica',
    'bold' => $fontDir . '/Helvetica-Bold',
    'italic' => $fontDir . '/Helvetica-Oblique',
    'bold_italic' => $fontDir . '/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $fontDir . '/ZapfDingbats',
    'bold' => $fontDir . '/ZapfDingbats',
    'italic' => $fontDir . '/ZapfDingbats',
    'bold_italic' => $fontDir . '/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $fontDir . '/Symbol',
    'bold' => $fontDir . '/Symbol',
    'italic' => $fontDir . '/Symbol',
    'bold_italic' => $fontDir . '/Symbol',
  ),
  'serif' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $fontDir . '/DejaVuSans-Bold',
    'bold_italic' => $fontDir . '/DejaVuSans-BoldOblique',
    'italic' => $fontDir . '/DejaVuSans-Oblique',
    'normal' => $fontDir . '/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $fontDir . '/DejaVuSansMono-Bold',
    'bold_italic' => $fontDir . '/DejaVuSansMono-BoldOblique',
    'italic' => $fontDir . '/DejaVuSansMono-Oblique',
    'normal' => $fontDir . '/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $fontDir . '/DejaVuSerif-Bold',
    'bold_italic' => $fontDir . '/DejaVuSerif-BoldItalic',
    'italic' => $fontDir . '/DejaVuSerif-Italic',
    'normal' => $fontDir . '/DejaVuSerif',
  ),
  'ipag' => array(
    'normal' => $fontDir . '/ipag',
    'bold' => $fontDir . '/ipag',
    'italic' => $fontDir . '/ipag',
    'bold_italic' => $fontDir . '/ipag',
  ),
  '07yasashisaantique' => array(
    'normal' => $fontDir . '/07YasashisaAntique',
    'bold' => $fontDir . '/07YasashisaAntique',
    'italic' => $fontDir . '/07YasashisaAntique',
    'bold_italic' => $fontDir . '/07YasashisaAntique',
  ),
  'genshingothic-bold' => array(
    'normal' => $fontDir . '/genshingothic_bold_normal_37c5bf2de43f9b39f8d1aee37f129bd7',
    'bold' => $fontDir . '/GenShinGothic-Bold',
    'italic' => $fontDir . '/GenShinGothic-Bold',
    'bold_italic' => $fontDir . '/GenShinGothic-Bold',
  ),
  'genshingothic-normal' => array(
    'normal' => $fontDir . '/GenShinGothic-Normal',
    'bold' => $fontDir . '/GenShinGothic-Normal',
    'italic' => $fontDir . '/GenShinGothic-Normal',
    'bold_italic' => $fontDir . '/GenShinGothic-Normal',
  ),
  'genshingothic-heavy' => array(
    'normal' => $fontDir . '/GenShinGothic-Heavy',
    'bold' => $fontDir . '/genshingothic_heavy_bold_1f525113059acecaa187ffe9f9474887',
    'italic' => $fontDir . '/GenShinGothic-Heavy',
    'bold_italic' => $fontDir . '/GenShinGothic-Heavy',
  ),
  'abeezee' => array(
    'normal' => $fontDir . '/Abeezee',
    'bold' => $fontDir . '/Abeezee',
    'italic' => $fontDir . '/Abeezee',
    'bold_italic' => $fontDir . '/Abeezee',
  ),
  'gnkiniro' => array(
    'normal' => $fontDir . '/Gnkiniro',
    'bold' => $fontDir . '/Gnkiniro',
    'italic' => $fontDir . '/Gnkiniro',
    'bold_italic' => $fontDir . '/Gnkiniro',
  ),
  'oswald' => array(
    'normal' => $fontDir . '/Oswald',
    'bold' => $fontDir . '/Oswald',
    'italic' => $fontDir . '/Oswald',
    'bold_italic' => $fontDir . '/Oswald',
  ),
  'rounded' => array(
    'normal' => $fontDir . '/Rounded',
    'bold' => $fontDir . '/Rounded',
    'italic' => $fontDir . '/Rounded',
    'bold_italic' => $fontDir . '/Rounded',
  ),
  'kintosans-regular' => array(
    'normal' => $fontDir . '/KintoSans-Regular',
    'bold' => $fontDir . '/KintoSans-Regular',
    'italic' => $fontDir . '/KintoSans-Regular',
    'bold_italic' => $fontDir . '/KintoSans-Regular',
  ),
  'kintosans-bold' => array(
    'normal' => $fontDir . '/KintoSans-Bold',
    'bold' => $fontDir . '/KintoSans-Bold',
    'italic' => $fontDir . '/KintoSans-Bold',
    'bold_italic' => $fontDir . '/KintoSans-Bold',
  ),
  'kintosans-black' => array(
    'normal' => $fontDir . '/KintoSans-Black',
    'bold' => $fontDir . '/KintoSans-Black',
    'italic' => $fontDir . '/KintoSans-Black',
    'bold_italic' => $fontDir . '/KintoSans-Black',
  ),
) ?>